name: Build and deploy PHP app to Azure Web App - time-tracker-testing

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x' # Choose your required Node.js version

      - name: Check if composer.json exists
        id: check_composer
        uses: andstor/file-existence-action@v1
        with:
          files: 'public/composer.json'

      - name: Run composer install if composer.json exists
        if: steps.check_composer.outputs.files_exists == 'true'
        run: |
          cd public
          composer validate --no-check-publish && composer install --prefer-dist --no-progress
          cd ..

      - name: Check if package.json exists
        id: check_package
        uses: andstor/file-existence-action@v1
        with:
          files: 'public/package.json'

      - name: Run npm install if package.json exists
        if: steps.check_package.outputs.files_exists == 'true'
        run: |
          cd public
          npm install
          cd ..

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: php-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: php-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_0B130164DC1B481ABEC803C765D55E0E }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_12D35014098A42879CF0573E6E4AA5D5 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_0BB2290D5242453296F20866C85EDDB6 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'time-tracker-testing'
          slot-name: 'Production'
          package: .
